### ISSUE TITLE
Questions for docs

### ISSUE THREAD

**Issue by patcon** [CivicTechTO/slack-greeting-bot#1]
Hey @sonalranjit, a couple questions so that this can be fully documented:

1. Where does this live? What's the name of the heroku app?
2. How is it deployed? Is it auto-deployed from master? Could it be? Could we use a ["deployment" section like this](https://github.com/CivicTechTO/women-and-color-frontend#deployment) as a template? I think only the heroku app owner can set up auto-deploy, so I'd need your help on that if it's not done already :)

**Comment by sonalranjit** [comment]
- I have connected autodeploy to heroku from the master branch. It lives here https://ctto-greetingbot.herokuapp.com/ i have updated the repo page to reflect this. 

- I will update the docs to reflect the deployment

**Comment by sonalranjit** [comment]
See #5 for update on this @patcon
